/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_minecade_deepend_nativeprot_DeependProtocol */

#ifndef _Included_com_minecade_deepend_nativeprot_DeependProtocol
#define _Included_com_minecade_deepend_nativeprot_DeependProtocol
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_minecade_deepend_nativeprot_DeependProtocol
 * Method:    initialize
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_minecade_deepend_nativeprot_DeependProtocol_initialize
  (JNIEnv *, jclass);

/*
 * Class:     com_minecade_deepend_nativeprot_DeependProtocol
 * Method:    destroy
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_minecade_deepend_nativeprot_DeependProtocol_destroy
  (JNIEnv *, jclass);

/*
 * Class:     com_minecade_deepend_nativeprot_DeependProtocol
 * Method:    loadNativeBuf
 * Signature: (I[B)[Lcom/minecade/deepend/nativeprot/NativeObj;
 */
JNIEXPORT jobjectArray JNICALL Java_com_minecade_deepend_nativeprot_DeependProtocol_loadNativeBuf
  (JNIEnv *, jclass, jint, jbyteArray);

#ifdef __cplusplus
}
#endif
#endif
