/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_minecade_deepend_nativeprot_DeependProtocol */

#ifndef _Included_com_minecade_deepend_nativeprot_DeependProtocol
#define _Included_com_minecade_deepend_nativeprot_DeependProtocol
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_minecade_deepend_nativeprot_DeependProtocol
 * Method:    readNativeBuf
 * Signature: (I[B)Lcom/minecade/deepend/nativeprot/NativeBuf;
 */
JNIEXPORT jobject JNICALL Java_com_minecade_deepend_nativeprot_DeependProtocol_readNativeBuf
  (JNIEnv *, jclass, jint, jbyteArray);

/*
 * Class:     com_minecade_deepend_nativeprot_DeependProtocol
 * Method:    writeNativeBuf
 * Signature: (ILcom/minecade/deepend/nativeprot/NativeObj;)Lcom/minecade/deepend/nativeprot/NativeBuf;
 */
JNIEXPORT jobject JNICALL Java_com_minecade_deepend_nativeprot_DeependProtocol_writeNativeBuf
  (JNIEnv *, jclass, jint, jobject);

#ifdef __cplusplus
}
#endif
#endif
